In [1]:
import numpy
import scipy.special

In [4]:
class Neural_Network():
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        print('Input Nodes: ', self.inodes, 'Hidden nodes: ', self.hnodes, 'Output nodes: ', self.onodes)
        
        # define out matrix
        
        self.wih = (numpy.random.rand(self.hnodes, self.inodes) - 0.5)
        self.who = (numpy.random.rand(self.onodes, self.hnodes) - 0.5)
        
        print('Matrix 1: \n', self.wih)
        print('Matrix 2: \n', self.who)
        
        self.lr = learningrate
        
        # Activation function
        self.activation_function = lambda x: scipy.special.expit(x)
        
    def train():
        pass
    
    def query():
        pass

In [5]:
n = Neural_Network(inputnodes=3, hiddennodes=5, outputnodes=2, learningrate=0.2)

Input Nodes:  3 Hidden nodes:  5 Output nodes:  2
Matrix 1: 
 [[-0.02822768 -0.07798171 -0.21167006]
 [-0.40952927 -0.46111085  0.49472333]
 [-0.19592154 -0.285138    0.42967609]
 [ 0.32667426  0.09884648  0.20653095]
 [-0.22111631  0.4036967  -0.29686998]]
Matrix 2: 
 [[-0.20347989  0.05771757  0.23720891 -0.30849618  0.48262342]
 [-0.37122079 -0.25255563 -0.38708885 -0.35284959  0.22440176]]
